# Generated by Django 4.0.6 on 2023-02-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='firstname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
