# Generated by Django 4.0.6 on 2023-02-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_message_username_message_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
    ]
